### PR TITLE
Update for macOS Ventura, 2023

### PR DESCRIPTION
**Pull request by DavidPhillipOster**
I couldn't get OpenGL to work reliably on some M1 Macs, so I rewrote the app to just use straight AppKit. The localizations were broken, so I fixed them too. I've tested on an Intel High Sierra machine in addition to M1 Mac Mini and M1 Air

### CODE REVIEW

**Comment by brummett** [comment]
Wow.  I haven't thought about this is a long time.  Thanks for getting it working again!  There goes the rest of my day :)

It builds and runs fine on my Intel Ventura laptop.

Commit [813d9b3](https://github.com/brummett/JewelToy/pull/1/commits/813d9b384c429eec5918e303e4a1455588f44504) didn't get all the places to get the executable named right.  I went into the Build Settings page in xcode and changed the "Product Name" from "jeweltoy" to "JewelToy" and then it would create the application with the right name, and it made a few more changes to JewelToy.xcodeproj/project.pbxproj    I can fix it on my end, or you can do it and push another commit.

I did try out your openGL branch.  It built and started the app, registered mouse clicks and played the sounds, but the window was just a plain gray square.  Not a big deal I guess, but if it's not going to work, then the reference to it in ReadMe.txt should be removed.

**Comment by DavidPhillipOster** [comment]
Thanks for the bug report! It's weird: the classic_opengl branch draws fine on the machines I have access to: an Intel High Sierra laptop, a Ventura M1 Mini, and and a Ventura M1 Air, but you aren't alone in complaining that it just draws gray (or whatever glColor() is set to.)

I'm still learning how to be a good contributor, so if you need the git commits squished to make a prettier git history, I'm willing to do it, but I may need some instruction.

I haven't gone through and added layout constraints in MainMenu.xib, and Preferences.xib so some of the text might get truncated in languages other than English.

**Comment by DavidPhillipOster** [comment]
Thanks! once I got the capitalization of the binary correct I could code-sign. In my private copy I also added the AppSandbox, and HardenedRuntime capabilities, and used my bundle ID prefix. My copy had some FinderInfo attributes on the `png`s in ejc_jt_hack and on About.xib and Preferences.xib.  Once I got rid of them using command lines like `xattr -d com.apple.FinderInfo Preferences.xib` I could Archive and Distribute the Release binary. https://github.com/DavidPhillipOster/JewelToy/releases/tag/1.3.2

**Comment by brummett** [comment]
Sorry about leaving this for so long.  Let's get this merged.

> if you need the git commits squished to make a prettier git history, I'm willing to do it,
> but I may need some instruction.

I'm fine with merging it as it is.  But if you'd like to fix things up a little, there are a few that might be worth combining:

* [9322b87](https://github.com/brummett/JewelToy/pull/1/commits/9322b8716b08dfb12a30eeb0a2e632e36f3b9d9d) and [74cb4c2](https://github.com/brummett/JewelToy/pull/1/commits/74cb4c233c037cf756b533c9276812c6f72ff9fd) (localizations for jp, fr, de, en)
* [813d9b3](https://github.com/brummett/JewelToy/pull/1/commits/813d9b384c429eec5918e303e4a1455588f44504) [3ff192c](https://github.com/brummett/JewelToy/pull/1/commits/3ff192cf0d167fa41d89525567fdd3e47636cbd7) (camel-case the app name)
* [3cb56c2](https://github.com/brummett/JewelToy/pull/1/commits/3cb56c2c140b696c16c4b91248a8e39d92619ce7), [7db12cb](https://github.com/brummett/JewelToy/pull/1/commits/7db12cbd7fcb0bfa1c7af6afa1bac93be1d44eaf), and [eaeb623](https://github.com/brummett/JewelToy/pull/1/commits/eaeb623e335ac967f0433cfcf3298306379133df) (removal of openGL)

I usually do these by doing an interactive rebase to move the like commits together, and using the "fixup" option on the second (and third) of each group so the rebase combines the subsequent commits of each group together with the first.  Have you done an interactive rebase before?

**Comment by DavidPhillipOster** [comment]
Thanks! I'll work on this today, and reply here when done. Also: I've a new branch, that I haven't pushed to github, swift_macos, where I've taken the whole app and rewritten it in Swift. 

The swift version almost finished: it's lacking the ability to use a folder of background images - you can pick the folder but it doesn't do anything with it yet.

One bug: you can give the app a set of alternate images for the jewels by dropping it in the image well in the Settings dialog, but once you do that the only way to get back to the built-in alternate images is to manually delete the alternate images from the ~/Library/Preferences file.

I made this set of alternate images, which makes the game really difficult:
sample

using this code to generate the file:

    // sample.swift - delete entitlements to allow writing to disk.

    import Cocoa

    @main
    class AppDelegate: NSObject, NSApplicationDelegate {

      @IBOutlet var window: NSWindow!

      func applicationDidFinishLaunching(_ aNotification: Notification) {
        let gemR = CGRect(x: 0, y: 0, width: 48, height: 48)
        let gemImage = NSImage(size: CGSize(width:48*7, height:48))
        gemImage.lockFocus()
        NSColor.clear.set()
        NSBezierPath(rect:gemR).fill()
        let attr:[NSAttributedString.Key : Any] = [.font : NSFont(name:"ArialNarrow-Bold", size:50)!,
           .foregroundColor : NSColor.yellow]
        for i in 0..<7 {
          let s = NSString(format:"%C", 0x2776 + i) // circled one: ❶
          s.draw(at:CGPoint(x: 2+(i*48), y: 0), withAttributes: attr)
        }
        gemImage.unlockFocus()
        do {
          try gemImage.tiffRepresentation?.write(to: URL(filePath: "/Users/Shared/sample.tiff"), options: .atomic)
        } catch {
          print("Unexpected error: \(error).")
        }
      }
    }

**Comment by DavidPhillipOster** [comment]
I've tried to clean up the git commit history as you recommended. Thanks for the direction!

**Comment by brummett** [comment]
> I made this set of alternate images, which makes the game really difficult

That's just evil.

> I've tried to clean up the git commit history as you recommended

This looks good to me.  If you're satisfied, I'll go ahead and merge.

**Comment by DavidPhillipOster** [comment]
I just pushed a fix for custom backgrounds to Master. So, now I'm good to merge.

(I'll send the Swift branch as a separate pull request.)

**Comment by DavidPhillipOster** [comment]
Note - the about box doesn't list your github repository. Consider adding that as an additional line

**Comment by DavidPhillipOster** [comment]
Thanks! to keep things clean I waited for you to merge. After you did that I pushed to https://github.com/DavidPhillipOster/JewelToy/tree/swift_mac the branch with the app rewritten in Swift.

**Pull request merged**
